name: extra_pedantic
description: Stricter Dart analyzer linter settings and best practices.
version: 5.0.0
homepage: https://github.com/modulovalue/extra_pedantic
repository: https://github.com/modulovalue/extra_pedantic
issue_tracker: https://github.com/modulovalue/extra_pedantic/issues

environment:
  sdk: '>=3.5.0 <4.0.0'
