name: extra_pedantic_extra
version: 1.0.0

publish_to: none

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  # To provide up-to-date information about officially supported lint rules
  linter:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: 3.5.0
      path: pkg/linter

dev_dependencies:
  extra_pedantic:
    path: ../extra_pedantic

dependency_overrides:
  _fe_analyzer_shared:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: 3.5.0
      path: pkg/_fe_analyzer_shared
  analyzer:
    git:
      url: https://github.com/dart-lang/sdk.git
      ref: 3.5.0
      path: pkg/analyzer

